name: BetterEconomy
main: me.SuperRonanCraft.BetterEconomy.BetterEconomy
version: '1.0.0'
api-version: '1.13'
author: SuperRonanCraft
depend: [Vault]
softdepend: [PlaceholderAPI]
load: STARTUP

commands:
  economy:
    aliases: [eco]
    description: Main economy command

permissions:
  bettereconomy.add:
    description: Add balance of other
  bettereconomy.remove:
    description: Remove from anothers balance
  bettereconomy.set:
    description: Set balance of other
  bettereconomy.pay:
    description: Pay one or more players
  bettereconomy.bal.other:
    description: Get balance of other
  bettereconomy.reload:
    description: Reload plugin